// src/constants.js o src/config/constants.js

export const initialMarcas = [
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "BAIC",
    "BMW",
    "Brilliance",
    "Changan",
    "Chery",
    "Chevrolet",
    "Chrysler",
    "Citroën",
    "DFM",
    "DFSK",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "Foton",
    "GAC Gonow",
    "Geely",
    "Great Wall",
    "Honda",
    "Hyundai",
    "Infiniti",
    "JAC",
    "Jaguar",
    "Jeep",
    "Kia",
    "Land Rover",
    "Lexus",
    "Lifan",
    "Mahindra",
    "Maserati",
    "Maxus",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "MG",
    "Mini",
    "Mitsubishi",
    "Nissan",
    "Opel",
    "Peugeot",
    "Porsche",
    "Renault",
    "Rolls-Royce",
    "SEAT",
    "Skoda",
    "SsangYong",
    "Subaru",
    "Suzuki",
    "Toyota",
    "Volkswagen",
    "Volvo",
    "Zotye",
];


// /src/constants/constants.js
export const CATEGORIES = [
    { value: "Filtros", label: "Filtros" },
    { value: "Suspensión y Dirección", label: "Suspensión y Dirección" },
    { value: "Motores", label: "Motores" },
    { value: "Radiadores", label: "Radiadores" },
    { value: "Bujías", label: "Bujías" },
    { value: "Iluminación", label: "Iluminación" },
    { value: "Distribución", label: "Distribución" },
    { value: "Carrocería", label: "Carrocería" },
    { value: "Encendido", label: "Encendido" },
    { value: "Frenos", label: "Frenos" },
    { value: "Topes de Cilindros", label: "Topes de Cilindros" },
    { value: "Embragues", label: "Embragues" },
    { value: "Inyección", label: "Inyección" },
    { value: "Aceites", label: "Aceites" },
    { value: "Correas de Accesorios", label: "Correas de Accesorios" },
    { value: "Bombas", label: "Bombas" },
    { value: "Block de Motores", label: "Block de Motores" },
    { value: "Espejos Retrovisores y Vidrios", label: "Espejos Retrovisores y Vidrios" },
    { value: "Sensores de Inyección", label: "Sensores de Inyección" },
    { value: "Barras y Piezas", label: "Barras y Piezas" },
    { value: "Parrillas y Brazos", label: "Parrillas y Brazos" },
    { value: "Manillas", label: "Manillas" },
    { value: "Cables de Comandos", label: "Cables de Comandos" },
    { value: "Instalaciones Eléctricas", label: "Instalaciones Eléctricas" },
    { value: "Transmisión", label: "Transmisión" },
    { value: "Motor", label: "Motor" },
    { value: "Interruptores", label: "Interruptores" },
    { value: "Calefacción", label: "Calefacción" },
    { value: "Bisagras", label: "Bisagras" },
    { value: "Distribuidores y Piezas", label: "Distribuidores y Piezas" },
    { value: "Embellecedores", label: "Embellecedores" },
    { value: "Portaequipajes", label: "Portaequipajes" },
    { value: "Selectoras y Cables", label: "Selectoras y Cables" },
    { value: "Repuestos de Exterior", label: "Repuestos de Exterior" },
    { value: "Alternadores y Piezas", label: "Alternadores y Piezas" },
    { value: "Electroventiladores", label: "Electroventiladores" },
    { value: "Semiejes y Homocinéticas", label: "Semiejes y Homocinéticas" },
    { value: "Dirección Hidráulica", label: "Dirección Hidráulica" },
    { value: "Chasis", label: "Chasis" },
    { value: "Cerraduras y Llaves", label: "Cerraduras y Llaves" },
    { value: "Alza Vidrios", label: "Alza Vidrios" },
    { value: "Componentes Electrónicos", label: "Componentes Electrónicos" },
    { value: "Tanques de Combustible", label: "Tanques de Combustible" },
    { value: "Aires Acondicionados", label: "Aires Acondicionados" },
    { value: "Molduras", label: "Molduras" },
    { value: "Paragolpes", label: "Paragolpes" },
    { value: "Carters de Motores", label: "Carters de Motores" },
    { value: "Sistemas de Refrigeración", label: "Sistemas de Refrigeración" },
    { value: "Componentes de Seguridad", label: "Componentes de Seguridad" },
    { value: "Sobrealimentación", label: "Sobrealimentación" },
];





