// src/constants.js o src/config/constants.js

export const initialMarcas = [
    "BAIC",
    "Brilliance",
    "Changan",
    "Chery",
    "Chevrolet",
    "Chrysler",
    "Citroën",
    "DFM",
    "DFSK",
    "Dodge",
    "Fiat",
    "Ford",
    "Foton",
    "GAC Gonow",
    "Geely",
    "Great Wall",
    "Honda",
    "Hyundai",
    "JAC",
    "Jaguar",
    "Kia",
    "Lifan",
    "Mahindra",
    "Maxus",
    "Mazda",
    "MG",
    "Mitsubishi",
    "Nissan",
    "Opel",
    "Peugeot",
    "Renault",
    "SEAT",
    "Skoda",
    "SsangYong",
    "Suzuki",
    "Toyota",
    "Volkswagen",
    "Zotye",
];

export const initialModelos = [
    "X35", "X55", "BJ40", "New X55 Plus", "All New X7", "UNI-K", "UNI-T", "X7 Plus",
    "New CS55 Plus", "Hunter", "New CS35 Plus", "New CS15", "CS15", "Alsvin",
    "Star Truck Plus", "MD201 Cabina simple", "MD201 Cargo Box", "MS201 Doble cabina",
    "M201 Furgón", "Omoda 5","tiggo","tiggo 3","tiggo 3 pro", "Tiggo 5x", "Tiggo 4", "Tiggo 8", "Tiggo 7", "Arrizo 5","Fulwin",
    "Sail", "Sail Hatchback", "Onix Sedán", "Onix Turbo", "Onix Turbo RS", "Colorado",
    "Captiva XL", "Trailblazer", "Tahoe", "Blazer", "Ranger", "Territory", "Escape",
    "Explorer", "Expedition", "Mustang", "F-150", "Bronco", "WR-V", "New HR-V",
    "New ZR-V", "New CR-V", "New Pilot", "The new TUCSON Híbrido", "The new TUCSON",
    "All new Santa FE Híbrido", "All new KONA Híbrido", "All New Kona", "New i20",
    "New GRAND i10 Sedan", "All New Accent", "New GRAND i10 Hatchback", "Venue",
    "New Creta", "Creta Grand", "All new Santa FE", "New PALISADE", "Porter Chasis",
    "Porter", "Porter Doble Cabina", "Staria Furgón", "STARIA", "Kona Eléctrico",
    "New Tucson Híbrido", "All New IONIQ 5", "Morning", "Soluto", "K3", "K3 Cross",
    "Sonet", "New Sonet", "Seltos", "Carens", "Sportage", "New Sorento", "Carnival",
    "Niro Híbrido", "Frontier", "EV6", "EV5", "EV9", "T60", "D60", "G10", "V80",
    "Euniq 5", "Euniq 6", "Euniq 7", "Deliver 9", "EV30", "EV80", "Corolla Cross",
    "Yaris Cross", "Corolla", "Hilux", "Fortuner", "RAV4", "Prado", "Land Cruiser",
    "4Runner", "Avanza", "Rush", "Hiace", "Coaster","4runner","Tercel","Beat", "Twincam ","Iq","FACE"
  ];

// /src/constants/constants.js
export const CATEGORIES = [
    { value: "Filtros", label: "Filtros" },
    { value: "Suspensión y Dirección", label: "Suspensión y Dirección" },
    { value: "Motores", label: "Motores" },
    { value: "Radiadores", label: "Radiadores" },
    { value: "Bujías", label: "Bujías" },
    { value: "Iluminación", label: "Iluminación" },
    { value: "Distribución", label: "Distribución" },
    { value: "Carrocería", label: "Carrocería" },
    { value: "Encendido", label: "Encendido" },
    { value: "Frenos", label: "Frenos" },
    { value: "Topes de Cilindros", label: "Topes de Cilindros" },
    { value: "Embragues", label: "Embragues" },
    { value: "Inyección", label: "Inyección" },
    { value: "Aceites", label: "Aceites" },
    { value: "Correas de Accesorios", label: "Correas de Accesorios" },
    { value: "Bombas", label: "Bombas" },
    { value: "Block de Motores", label: "Block de Motores" },
    { value: "Espejos Retrovisores y Vidrios", label: "Espejos Retrovisores y Vidrios" },
    { value: "Sensores de Inyección", label: "Sensores de Inyección" },
    { value: "Barras y Piezas", label: "Barras y Piezas" },
    { value: "Parrillas y Brazos", label: "Parrillas y Brazos" },
    { value: "Manillas", label: "Manillas" },
    { value: "Cables de Comandos", label: "Cables de Comandos" },
    { value: "Instalaciones Eléctricas", label: "Instalaciones Eléctricas" },
    { value: "Transmisión", label: "Transmisión" },
    { value: "Motor", label: "Motor" },
    { value: "Interruptores", label: "Interruptores" },
    { value: "Calefacción", label: "Calefacción" },
    { value: "Bisagras", label: "Bisagras" },
    { value: "Distribuidores y Piezas", label: "Distribuidores y Piezas" },
    { value: "Embellecedores", label: "Embellecedores" },
    { value: "Portaequipajes", label: "Portaequipajes" },
    { value: "Selectoras y Cables", label: "Selectoras y Cables" },
    { value: "Repuestos de Exterior", label: "Repuestos de Exterior" },
    { value: "Alternadores y Piezas", label: "Alternadores y Piezas" },
    { value: "Electroventiladores", label: "Electroventiladores" },
    { value: "Semiejes y Homocinéticas", label: "Semiejes y Homocinéticas" },
    { value: "Dirección Hidráulica", label: "Dirección Hidráulica" },
    { value: "Chasis", label: "Chasis" },
    { value: "Cerraduras y Llaves", label: "Cerraduras y Llaves" },
    { value: "Alza Vidrios", label: "Alza Vidrios" },
    { value: "Componentes Electrónicos", label: "Componentes Electrónicos" },
    { value: "Tanques de Combustible", label: "Tanques de Combustible" },
    { value: "Aires Acondicionados", label: "Aires Acondicionados" },
    { value: "Molduras", label: "Molduras" },
    { value: "Paragolpes", label: "Paragolpes" },
    { value: "Carters de Motores", label: "Carters de Motores" },
    { value: "Sistemas de Refrigeración", label: "Sistemas de Refrigeración" },
    { value: "Componentes de Seguridad", label: "Componentes de Seguridad" },
    { value: "Sobrealimentación", label: "Sobrealimentación" },
];


export const tienda = [
    { src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBd52oJwbk2yXum3Ons59Xs_nFeul7Z7kK7w&s', alt: 'RepuestosCoroca' },
    { src: 'https://cdn.worldvectorlogo.com/logos/mercadolibre.svg', alt: 'MercadoLibre' },
    { src: 'https://http2.mlstatic.com/D_NQ_NP_790984-MLA78333190102_082024-F.jpg', alt: 'RepuestosMaracars' },
    { src: 'https://repuestoscr.com.do/wp-content/uploads/sites/248/2022/05/logo.jpg', alt: 'RepuestosCYR' },
    { src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvM45GeQwsnw244fJUIQHMVgWY776TF11X6w&s', alt: 'Bolomey' },
]
    





